
خطا در دریافت شناسه‌ی lokhtone: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/lokhtone/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی malihe_ahz: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/malihe_ahz/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی nargis__an: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/nargis__an/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی sarafarahbakhsh1982: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/sarafarahbakhsh1982/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی ms_m_aalamii: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/ms_m_aalamii/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی pwrmhmd4876: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/pwrmhmd4876/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی clinic_denizz: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/clinic_denizz/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی behnaz_kaz: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/behnaz_kaz/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی zahrasalehi8170: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/zahrasalehi8170/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی fatima_gholmaiii: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/fatima_gholmaiii/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی skincareava7: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/skincareava7/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی fatemezahra13988: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/fatemezahra13988/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی mahsa_elahi375: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/mahsa_elahi375/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی neda_moniri: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/neda_moniri/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی turaldoor: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/turaldoor/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی d541rr18: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/d541rr18/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی zahra.enayati.7667: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/zahra.enayati.7667/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی a.r.s.77777777: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/a.r.s.77777777/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی nazi_h12303: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/nazi_h12303/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی akramdamvari: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/akramdamvari/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی nm_136222: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/nm_136222/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی __mohammadd__reza__: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/__mohammadd__reza__/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی fatemejavan_tkd: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/fatemejavan_tkd/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی _sarey_1381: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/_sarey_1381/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی skincare.karami.68sm: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/skincare.karami.68sm/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی niloofarabdollahnam: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/niloofarabdollahnam/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی roshana.building: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/roshana.building/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی mitra.e.n: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/mitra.e.n/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی afsoon_gholipoor: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/afsoon_gholipoor/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی mis_ftmh: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/mis_ftmh/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی bighamzahra7: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/bighamzahra7/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی nameis.mobina: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/nameis.mobina/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی nadiya_radfar: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/nadiya_radfar/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی khanomi1375_75: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/khanomi1375_75/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی fb4320588: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/fb4320588/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی m_ahmadii84: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/m_ahmadii84/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی mzarepor97: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/mzarepor97/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی mohaddeseh_fakoor: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/mohaddeseh_fakoor/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی mahi__rad.1382: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/mahi__rad.1382/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی neda_rad_31: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/neda_rad_31/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی call_me_eliiii: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/call_me_eliiii/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی spydhqsmy89: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/spydhqsmy89/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی nafas.z.zamen: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/nafas.z.zamen/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی mahta.salehi_: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/mahta.salehi_/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی zohreyosefi27: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/zohreyosefi27/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی 5805__nazanin: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/5805__nazanin/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی parisar7779000: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/parisar7779000/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی atfh51592023: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/atfh51592023/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی nazlilipood: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/nazlilipood/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی javadbami57: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/javadbami57/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی ashoori223: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/ashoori223/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی n.f.o.1369: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/n.f.o.1369/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی anah.ita6473: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/anah.ita6473/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی rosegarden_403: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/rosegarden_403/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی farzane.behboodi: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/farzane.behboodi/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی mahasa155: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/mahasa155/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در ارسال پیام به lawyer_zahra_zvr: challenge_required
خطا در دریافت شناسه‌ی nazi.ranjba: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/nazi.ranjba/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی shahnaz.mozaffari_pmu: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/shahnaz.mozaffari_pmu/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی e1.telgerdy: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/e1.telgerdy/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی zainab.mirzaei99: challenge_required
خطا در دریافت شناسه‌ی mahnaz723312: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/mahnaz723312/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی sarasafamanesh6: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/sarasafamanesh6/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی ma_rzieh83: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/ma_rzieh83/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی roshiii94: challenge_required
خطا در دریافت شناسه‌ی yaldaa6199: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/yaldaa6199/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی atrisa13942022: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/atrisa13942022/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی _zahra_5_23: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/_zahra_5_23/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی zahmatinafise: challenge_required
خطا در دریافت شناسه‌ی ziba__nazmy: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/ziba__nazmy/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی saha_rsafamanesh: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/saha_rsafamanesh/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی yasaman.e76: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/yasaman.e76/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی mahbubeabasi699: challenge_required
خطا در دریافت شناسه‌ی mahtabtoraby: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/mahtabtoraby/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی arzwnsyrly: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/arzwnsyrly/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی n_z_rasna: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/n_z_rasna/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی aye_aysan: challenge_required
خطا در دریافت شناسه‌ی zahra_.5711: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/zahra_.5711/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی sanazhashemzadeh69: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/sanazhashemzadeh69/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی alismaily41: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/alismaily41/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی nghasemi10: challenge_required
خطا در دریافت شناسه‌ی fatemeh000055: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/fatemeh000055/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی n_asri_nv: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/n_asri_nv/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی hd_samsaam: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/hd_samsaam/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی frshteh_tj: challenge_required
خطا در دریافت شناسه‌ی fatme.mohmdi051: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/fatme.mohmdi051/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی moghdam.sanam: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/moghdam.sanam/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی s_d_n37657: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/s_d_n37657/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی nahid_gharavol: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /challenge/ (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1028)')))
خطا در دریافت شناسه‌ی fekri2321: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/fekri2321/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی shahbazi1263: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/shahbazi1263/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی lokhtone: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/lokhtone/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت شناسه‌ی malihe_ahz: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/malihe_ahz/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت اطلاعات کاربر lokhtone: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/lokhtone/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در ارسال پیام به lokhtone: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/lokhtone/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت اطلاعات کاربر nm_136222: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/nm_136222/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در دریافت اطلاعات کاربر __mohammadd__reza__: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/__mohammadd__reza__/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
⚠️ خطا در دریافت شناسه‌ی nm_136222: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/nm_136222/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
خطا در ارسال پیام به mitra.e.n: {"action":"item_ack","status_code":"403","message":"We're sorry, but something went wrong. Please try again.","payload":{"client_context":"6800093281850123802","message":"We're sorry, but something went wrong. Please try again.","client_facing_error_message":"Your message can't be delivered. There is a limit to the number of new conversations you can start every 24 hours with people who don't follow you.","error_code":"1545119","can_see_notes":"True","can_see_broadcast_chats":"True"},"status":"fail"}
خطا در دریافت اطلاعات کاربر bighamzahra7: SSLError HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/bighamzahra7/usernameinfo/ (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1028)')))
خطا در ارسال پیام به nameis.mobina: {"action":"item_ack","status_code":"403","message":"We're sorry, but something went wrong. Please try again.","payload":{"client_context":"6800054903121701298","message":"We're sorry, but something went wrong. Please try again.","client_facing_error_message":"Your message can't be delivered. There is a limit to the number of new conversations you can start every 24 hours with people who don't follow you.","error_code":"1545119","can_see_notes":"True","can_see_broadcast_chats":"True"},"status":"fail"}
خطا در ارسال پیام به bighamzahra7: {"action":"item_ack","status_code":"403","message":"We're sorry, but something went wrong. Please try again.","payload":{"client_context":"6800094683998124985","message":"We're sorry, but something went wrong. Please try again.","client_facing_error_message":"Your message can't be delivered. There is a limit to the number of new conversations you can start every 24 hours with people who don't follow you.","error_code":"1545119","can_see_notes":"True","can_see_broadcast_chats":"True"},"status":"fail"}
خطا در ارسال پیام به khanomi1375_75: {"action":"item_ack","status_code":"403","message":"We're sorry, but something went wrong. Please try again.","payload":{"client_context":"6800090033964841072","message":"We're sorry, but something went wrong. Please try again.","client_facing_error_message":"Your message can't be delivered. There is a limit to the number of new conversations you can start every 24 hours with people who don't follow you.","error_code":"1545119","can_see_notes":"True","can_see_broadcast_chats":"True"},"status":"fail"}
خطا در ارسال پیام به bighamzahra7: {"action":"item_ack","status_code":"403","message":"We're sorry, but something went wrong. Please try again.","payload":{"client_context":"6800067841987829828","message":"We're sorry, but something went wrong. Please try again.","client_facing_error_message":"Your message can't be delivered. There is a limit to the number of new conversations you can start every 24 hours with people who don't follow you.","error_code":"1545119","can_see_notes":"True","can_see_broadcast_chats":"True"},"status":"fail"}
خطا در ارسال پیام به khanomi1375_75: {"action":"item_ack","status_code":"403","message":"We're sorry, but something went wrong. Please try again.","payload":{"client_context":"6800031096122671215","message":"We're sorry, but something went wrong. Please try again.","client_facing_error_message":"Your message can't be delivered. There is a limit to the number of new conversations you can start every 24 hours with people who don't follow you.","error_code":"1545119","can_see_notes":"True","can_see_broadcast_chats":"True"},"status":"fail"}
خطا در ارسال پیام به m_ahmadii84: {"action":"item_ack","status_code":"403","message":"We're sorry, but something went wrong. Please try again.","payload":{"client_context":"6800072332488561243","message":"We're sorry, but something went wrong. Please try again.","client_facing_error_message":"Your message can't be delivered. There is a limit to the number of new conversations you can start every 24 hours with people who don't follow you.","error_code":"1545119","can_see_notes":"True","can_see_broadcast_chats":"True"},"status":"fail"}
خطا در ارسال پیام به mzarepor97: {"action":"item_ack","status_code":"403","message":"We're sorry, but something went wrong. Please try again.","payload":{"client_context":"6800031669455824164","message":"We're sorry, but something went wrong. Please try again.","client_facing_error_message":"Your message can't be delivered. There is a limit to the number of new conversations you can start every 24 hours with people who don't follow you.","error_code":"1545119","can_see_notes":"True","can_see_broadcast_chats":"True"},"status":"fail"}
خطا در ارسال پیام به mahi__rad.1382: {"action":"item_ack","status_code":"403","message":"We're sorry, but something went wrong. Please try again.","payload":{"client_context":"6800037695921136826","message":"We're sorry, but something went wrong. Please try again.","client_facing_error_message":"Your message can't be delivered. There is a limit to the number of new conversations you can start every 24 hours with people who don't follow you.","error_code":"1545119","can_see_notes":"True","can_see_broadcast_chats":"True"},"status":"fail"}
خطا در ارسال پیام به neda_rad_31: {"action":"item_ack","status_code":"403","message":"We're sorry, but something went wrong. Please try again.","payload":{"client_context":"6800070576907590930","message":"We're sorry, but something went wrong. Please try again.","client_facing_error_message":"Your message can't be delivered. There is a limit to the number of new conversations you can start every 24 hours with people who don't follow you.","error_code":"1545119","can_see_notes":"True","can_see_broadcast_chats":"True"},"status":"fail"}
خطا در ارسال پیام به spydhqsmy89: {"action":"item_ack","status_code":"403","message":"We're sorry, but something went wrong. Please try again.","payload":{"client_context":"6800020500202654956","message":"We're sorry, but something went wrong. Please try again.","client_facing_error_message":"Your message can't be delivered. There is a limit to the number of new conversations you can start every 24 hours with people who don't follow you.","error_code":"1545119","can_see_notes":"True","can_see_broadcast_chats":"True"},"status":"fail"}
خطا در ارسال پیام به nafas.z.zamen: {"action":"item_ack","status_code":"403","message":"We're sorry, but something went wrong. Please try again.","payload":{"client_context":"6800084349223052313","message":"We're sorry, but something went wrong. Please try again.","client_facing_error_message":"Your message can't be delivered. There is a limit to the number of new conversations you can start every 24 hours with people who don't follow you.","error_code":"1545119","can_see_notes":"True","can_see_broadcast_chats":"True"},"status":"fail"}
